# Generated by Django 5.0.1 on 2024-01-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
