# Generated by Django 5.0.1 on 2024-01-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0002_todo_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='todo_task',
            name='updated_at',
        ),
    ]
