# Generated by Django 5.0.1 on 2024-01-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0003_remove_todo_task_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo_task',
            old_name='todoID',
            new_name='id',
        ),
    ]
