# Generated by Django 5.0.1 on 2024-01-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
